[package]
name = "adas_pilot"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"]}
image = "0.25.9"
imageproc = "0.25.0"
ndarray = "0.17.1"
numpy = "0.27.1"

[build-dependencies]
pyo3-build-config = "0.21"
